---
  extends: ./node.yml
  parser: babel-eslint
  env:
    node: true
    es6: true
  rules:
    #require parens in arrow function arguments
    arrow-parens:
      - 2
      - as-needed
    #require space before/after arrow function's arrow
    arrow-spacing:
      - 2
      -
        before: true
        after: true
    #verify calls of super() in constructors
    constructor-super: 1
    #enforce spacing around the * in generator functions
    generator-star-spacing:
      - 2
      -
        before: true
        after: false
    #disallow modifying variables of class declarations
    no-class-assign: 1
    #disallow modifying variables that are declared using const
    no-const-assign: 2
    #disallow use of this/super before calling super() in constructors.
    no-this-before-super: 1
    #require let or const instead of var
    no-var: 2
    #require method and property shorthand syntax for object literals
    object-shorthand:
      - 2
      - always
    #suggest using const declaration for variables that are never modified after declared
    prefer-const: 1
    #suggest using the spread operator instead of .apply().
    prefer-spread: 1
    #suggest using Reflect methods where applicable
    prefer-reflect: 1
    #disallow generator functions that do not have yield
    require-yield: 2
